name: Deployment
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  Docker-Build:
    uses: ./.github/workflows/docker.yaml
    with:
      dockerfileLocation: Dockerfile
  
  Sonar-Scan:
    uses: ./.github/workflows/sonarr.yaml
    with:
      sourceLocation: ./src

  Dependencies-Dev:
    needs: [Docker-Build, Sonar-Scan]
    uses: ./.github/workflows/terraform.yaml
    with:
      terraform_version: 1.1.7
      deploymentEnvironment: dev
      terraform_project_prefix: ProjectEverest
    secrets: inherit

  Helm-Dev:
    needs: [Dependencies-Dev]
    uses: ./.github/workflows/helm.yaml
    with:
      vaultUrl: https://vault-dev-wsp-poc-public-vault-54e9fb45.2cc7f94d.z1.hashicorp.cloud:8200
      chartPath: ./charts/everest
      deploymentEnvironment: dev
      deploymentName: project-everest
    secrets: inherit

  Dependencies-Test:
    needs: [Helm-Dev]
    uses: ./.github/workflows/terraform.yaml
    with:
      terraform_version: 1.1.7
      deploymentEnvironment: test
      terraform_project_prefix: ProjectEverest
    secrets: inherit

  Helm-Test:
    needs: [Dependencies-Test]
    uses: ./.github/workflows/helm.yaml
    with:
      vaultUrl: https://vault-dev-wsp-poc-public-vault-54e9fb45.2cc7f94d.z1.hashicorp.cloud:8200
      chartPath: ./charts/everest
      deploymentEnvironment: test
      deploymentName: project-everest
    secrets: inherit

  Dependencies-Staging:
    needs: [Helm-Test]
    uses: ./.github/workflows/terraform.yaml
    with:
      terraform_version: 1.1.7
      deploymentEnvironment: staging
      terraform_project_prefix: ProjectEverest
    secrets: inherit

  Helm-Staging:
    needs: [Dependencies-Staging]
    uses: ./.github/workflows/helm.yaml
    with:
      vaultUrl: https://vault-dev-wsp-poc-public-vault-54e9fb45.2cc7f94d.z1.hashicorp.cloud:8200
      chartPath: ./charts/everest
      deploymentEnvironment: staging
      deploymentName: project-everest
    secrets: inherit

  Dependencies-Prod:
    needs: [Helm-Staging]
    uses: ./.github/workflows/terraform.yaml
    with:
      terraform_version: 1.1.7
      deploymentEnvironment: prod
      terraform_project_prefix: ProjectEverest
    secrets: inherit

  Helm-Prod:
    needs: [Dependencies-Prod]
    uses: ./.github/workflows/helm.yaml
    with:
      vaultUrl: https://vault-dev-wsp-poc-public-vault-54e9fb45.2cc7f94d.z1.hashicorp.cloud:8200
      chartPath: ./charts/everest
      deploymentEnvironment: prod
      deploymentName: project-everest
    secrets: inherit