name: Helm Deploy
on:
  workflow_call:
    inputs:
      vaultUrl:
        required: true
        type: string
      chartPath:
        required: true
        type: string
      deploymentEnvironment:
        required: true
        type: string
      deploymentName:
        required: true
        type: string

jobs:
  helm:
    name: 'Helm'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          method: token
          url: ${{ inputs.vaultUrl }}
          token: ${{ secrets.VAULT_TOKEN }}
          namespace: admin/wsp
          secrets: |
            secrets/wsp-aks-dev-eus2-xrnv kubeconfig | KUBE_CONFIG;

      - name: Create kube config
        run: |
          mkdir -p $HOME/.kube/
          echo "${{ steps.secrets.outputs.KUBE_CONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Install helm
        run: |
          curl -LO https://get.helm.sh/helm-v3.8.0-linux-amd64.tar.gz
          tar -zxvf helm-v3.8.0-linux-amd64.tar.gz
          mv linux-amd64/helm /usr/local/bin/helm
          helm version
      
      - name: Lint Helm
        working-directory: ${{ inputs.chartPath }}
        run: helm lint .

      - name: Deploy Helm
        working-directory: ${{ inputs.chartPath }}
        run: helm upgrade --install ${{ inputs.deploymentName }} .