name: Sonar Scan
on:
  workflow_call:
    inputs:
      sourceLocation:
        required: true
        type: string

jobs:
  docker:
    name: 'Sonar Scan'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: echo "doing a scan..."